version: "3.8"

services:
  server: # function: It should have a look at incoming requests and funnel them to PHP container
    image: 'nginx:stable-alpine' # ref: https://hub.docker.com/_/nginx
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # bind mount single file
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated 
      # delegated: 
      # If container should write some data there, 
      # it's not instantly reflected back to the host machine
  mysql:
    image: mysql:5.7 # ref: https://hub.docker.com/_/mysql
    env_file:
      - ./env/mysql.env
  # composer:
  # artison:
  # npm: